services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: comic-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-royal-resonance-aquste56-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner
      - SPRING_DATASOURCE_PASSWORD=npg_7NhPdBM5Xues
      - APP_CACHE_DIR=/app/image_cache
      - APP_EXTENSIONS_DIR=/app/extensions
      - APP_SCRAPER_RUNNER_PATH=/app/scraper/runner.js
    volumes:
      - ./backend/extensions:/app/extensions
      - ./backend/image_cache:/app/image_cache

  tunnel:
    image: node:20-alpine
    container_name: comic-tunnel
    restart: always
    command: npx localtunnel --port 8080 --local-host backend --subdomain comic-aggregator-duy-trum
    depends_on:
      - backend
